/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";

export interface IBerachainRewardsRegistryInterface extends utils.Interface {
  functions: {
    "DOLOMITE_MARGIN()": FunctionFragment;
    "berachainRewardsFactory()": FunctionFragment;
    "bgt()": FunctionFragment;
    "bgtIsolationModeVaultFactory()": FunctionFragment;
    "bgtm()": FunctionFragment;
    "bgtmIsolationModeVaultFactory()": FunctionFragment;
    "calculateMetaVaultByAccount(address)": FunctionFragment;
    "createMetaVault(address,address)": FunctionFragment;
    "dolomiteRegistry()": FunctionFragment;
    "getAccountByMetaVault(address)": FunctionFragment;
    "getAccountToAssetToDefaultType(address,address)": FunctionFragment;
    "getMetaVaultByAccount(address)": FunctionFragment;
    "getMetaVaultByVault(address)": FunctionFragment;
    "iBgt()": FunctionFragment;
    "iBgtIsolationModeVaultFactory()": FunctionFragment;
    "iBgtStakingVault()": FunctionFragment;
    "infrared()": FunctionFragment;
    "metaVaultImplementation()": FunctionFragment;
    "ownerSetBerachainRewardsFactory(address)": FunctionFragment;
    "ownerSetBgt(address)": FunctionFragment;
    "ownerSetBgtIsolationModeVaultFactory(address)": FunctionFragment;
    "ownerSetBgtm(address)": FunctionFragment;
    "ownerSetBgtmIsolationModeVaultFactory(address)": FunctionFragment;
    "ownerSetDolomiteRegistry(address)": FunctionFragment;
    "ownerSetIBgt(address)": FunctionFragment;
    "ownerSetIBgtIsolationModeVaultFactory(address)": FunctionFragment;
    "ownerSetIBgtStakingVault(address)": FunctionFragment;
    "ownerSetInfrared(address)": FunctionFragment;
    "ownerSetMetaVaultImplementation(address)": FunctionFragment;
    "ownerSetPolFeeAgent(address)": FunctionFragment;
    "ownerSetPolFeePercentage(uint256)": FunctionFragment;
    "ownerSetPolLiquidator(address)": FunctionFragment;
    "ownerSetPolUnwrapperTrader(address)": FunctionFragment;
    "ownerSetPolWrapperTrader(address)": FunctionFragment;
    "ownerSetRewardVaultOverride(address,uint8,address)": FunctionFragment;
    "ownerSetWbera(address)": FunctionFragment;
    "polFeeAgent()": FunctionFragment;
    "polFeePercentage(uint256)": FunctionFragment;
    "polLiquidator()": FunctionFragment;
    "polUnwrapperTrader()": FunctionFragment;
    "polWrapperTrader()": FunctionFragment;
    "rewardVault(address,uint8)": FunctionFragment;
    "setDefaultRewardVaultTypeFromMetaVaultByAsset(address,uint8)": FunctionFragment;
    "wbera()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DOLOMITE_MARGIN"
      | "berachainRewardsFactory"
      | "bgt"
      | "bgtIsolationModeVaultFactory"
      | "bgtm"
      | "bgtmIsolationModeVaultFactory"
      | "calculateMetaVaultByAccount"
      | "createMetaVault"
      | "dolomiteRegistry"
      | "getAccountByMetaVault"
      | "getAccountToAssetToDefaultType"
      | "getMetaVaultByAccount"
      | "getMetaVaultByVault"
      | "iBgt"
      | "iBgtIsolationModeVaultFactory"
      | "iBgtStakingVault"
      | "infrared"
      | "metaVaultImplementation"
      | "ownerSetBerachainRewardsFactory"
      | "ownerSetBgt"
      | "ownerSetBgtIsolationModeVaultFactory"
      | "ownerSetBgtm"
      | "ownerSetBgtmIsolationModeVaultFactory"
      | "ownerSetDolomiteRegistry"
      | "ownerSetIBgt"
      | "ownerSetIBgtIsolationModeVaultFactory"
      | "ownerSetIBgtStakingVault"
      | "ownerSetInfrared"
      | "ownerSetMetaVaultImplementation"
      | "ownerSetPolFeeAgent"
      | "ownerSetPolFeePercentage"
      | "ownerSetPolLiquidator"
      | "ownerSetPolUnwrapperTrader"
      | "ownerSetPolWrapperTrader"
      | "ownerSetRewardVaultOverride"
      | "ownerSetWbera"
      | "polFeeAgent"
      | "polFeePercentage"
      | "polLiquidator"
      | "polUnwrapperTrader"
      | "polWrapperTrader"
      | "rewardVault"
      | "setDefaultRewardVaultTypeFromMetaVaultByAsset"
      | "wbera"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DOLOMITE_MARGIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "berachainRewardsFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bgt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bgtIsolationModeVaultFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bgtm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bgtmIsolationModeVaultFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateMetaVaultByAccount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createMetaVault",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "dolomiteRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountByMetaVault",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountToAssetToDefaultType",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMetaVaultByAccount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMetaVaultByVault",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "iBgt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "iBgtIsolationModeVaultFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "iBgtStakingVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "infrared", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "metaVaultImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetBerachainRewardsFactory",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "ownerSetBgt", values: [string]): string;
  encodeFunctionData(
    functionFragment: "ownerSetBgtIsolationModeVaultFactory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetBgtm",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetBgtmIsolationModeVaultFactory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetDolomiteRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetIBgt",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetIBgtIsolationModeVaultFactory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetIBgtStakingVault",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetInfrared",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetMetaVaultImplementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetPolFeeAgent",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetPolFeePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetPolLiquidator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetPolUnwrapperTrader",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetPolWrapperTrader",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetRewardVaultOverride",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetWbera",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "polFeeAgent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "polFeePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "polLiquidator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "polUnwrapperTrader",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "polWrapperTrader",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardVault",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultRewardVaultTypeFromMetaVaultByAsset",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "wbera", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DOLOMITE_MARGIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "berachainRewardsFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bgt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bgtIsolationModeVaultFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bgtm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bgtmIsolationModeVaultFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateMetaVaultByAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMetaVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dolomiteRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountByMetaVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountToAssetToDefaultType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetaVaultByAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetaVaultByVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "iBgt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "iBgtIsolationModeVaultFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "iBgtStakingVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "infrared", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "metaVaultImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetBerachainRewardsFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetBgt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetBgtIsolationModeVaultFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetBgtm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetBgtmIsolationModeVaultFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetDolomiteRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetIBgt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetIBgtIsolationModeVaultFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetIBgtStakingVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetInfrared",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetMetaVaultImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetPolFeeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetPolFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetPolLiquidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetPolUnwrapperTrader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetPolWrapperTrader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetRewardVaultOverride",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetWbera",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "polFeeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "polFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "polLiquidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "polUnwrapperTrader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "polWrapperTrader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultRewardVaultTypeFromMetaVaultByAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wbera", data: BytesLike): Result;

  events: {};
}

export interface IBerachainRewardsRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBerachainRewardsRegistryInterface;

  functions: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<[string]>;

    berachainRewardsFactory(overrides?: CallOverrides): Promise<[string]>;

    bgt(overrides?: CallOverrides): Promise<[string]>;

    bgtIsolationModeVaultFactory(overrides?: CallOverrides): Promise<[string]>;

    bgtm(overrides?: CallOverrides): Promise<[string]>;

    bgtmIsolationModeVaultFactory(overrides?: CallOverrides): Promise<[string]>;

    calculateMetaVaultByAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    createMetaVault(
      _account: string,
      _vault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    dolomiteRegistry(overrides?: CallOverrides): Promise<[string]>;

    getAccountByMetaVault(
      _metaVault: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getAccountToAssetToDefaultType(
      _account: string,
      _asset: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getMetaVaultByAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMetaVaultByVault(
      _vault: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    iBgt(overrides?: CallOverrides): Promise<[string]>;

    iBgtIsolationModeVaultFactory(overrides?: CallOverrides): Promise<[string]>;

    iBgtStakingVault(overrides?: CallOverrides): Promise<[string]>;

    infrared(overrides?: CallOverrides): Promise<[string]>;

    metaVaultImplementation(overrides?: CallOverrides): Promise<[string]>;

    ownerSetBerachainRewardsFactory(
      _berachainRewardsFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetBgt(
      _bgt: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetBgtIsolationModeVaultFactory(
      _bgtIsolationModeVaultFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetBgtm(
      _bgtm: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetBgtmIsolationModeVaultFactory(
      _bgtmIsolationModeVaultFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetDolomiteRegistry(
      _dolomiteRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetIBgt(
      _iBgt: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetIBgtIsolationModeVaultFactory(
      _iBgtIsolationModeVaultFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetIBgtStakingVault(
      _iBgtStakingVault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetInfrared(
      _infrared: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetMetaVaultImplementation(
      _metaVaultImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetPolFeeAgent(
      _polFeeAgent: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetPolFeePercentage(
      _polFeePercentage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetPolLiquidator(
      _polLiquidator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetPolUnwrapperTrader(
      _polUnwrapperTrader: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetPolWrapperTrader(
      _polWrapperTrader: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetRewardVaultOverride(
      _asset: string,
      _type: BigNumberish,
      _rewardVault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetWbera(
      _wbera: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    polFeeAgent(overrides?: CallOverrides): Promise<[string]>;

    polFeePercentage(
      _marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    polLiquidator(overrides?: CallOverrides): Promise<[string]>;

    polUnwrapperTrader(overrides?: CallOverrides): Promise<[string]>;

    polWrapperTrader(overrides?: CallOverrides): Promise<[string]>;

    rewardVault(
      _asset: string,
      _type: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setDefaultRewardVaultTypeFromMetaVaultByAsset(
      _asset: string,
      _type: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    wbera(overrides?: CallOverrides): Promise<[string]>;
  };

  DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<string>;

  berachainRewardsFactory(overrides?: CallOverrides): Promise<string>;

  bgt(overrides?: CallOverrides): Promise<string>;

  bgtIsolationModeVaultFactory(overrides?: CallOverrides): Promise<string>;

  bgtm(overrides?: CallOverrides): Promise<string>;

  bgtmIsolationModeVaultFactory(overrides?: CallOverrides): Promise<string>;

  calculateMetaVaultByAccount(
    _account: string,
    overrides?: CallOverrides
  ): Promise<string>;

  createMetaVault(
    _account: string,
    _vault: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  dolomiteRegistry(overrides?: CallOverrides): Promise<string>;

  getAccountByMetaVault(
    _metaVault: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getAccountToAssetToDefaultType(
    _account: string,
    _asset: string,
    overrides?: CallOverrides
  ): Promise<number>;

  getMetaVaultByAccount(
    _account: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getMetaVaultByVault(
    _vault: string,
    overrides?: CallOverrides
  ): Promise<string>;

  iBgt(overrides?: CallOverrides): Promise<string>;

  iBgtIsolationModeVaultFactory(overrides?: CallOverrides): Promise<string>;

  iBgtStakingVault(overrides?: CallOverrides): Promise<string>;

  infrared(overrides?: CallOverrides): Promise<string>;

  metaVaultImplementation(overrides?: CallOverrides): Promise<string>;

  ownerSetBerachainRewardsFactory(
    _berachainRewardsFactory: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetBgt(
    _bgt: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetBgtIsolationModeVaultFactory(
    _bgtIsolationModeVaultFactory: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetBgtm(
    _bgtm: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetBgtmIsolationModeVaultFactory(
    _bgtmIsolationModeVaultFactory: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetDolomiteRegistry(
    _dolomiteRegistry: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetIBgt(
    _iBgt: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetIBgtIsolationModeVaultFactory(
    _iBgtIsolationModeVaultFactory: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetIBgtStakingVault(
    _iBgtStakingVault: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetInfrared(
    _infrared: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetMetaVaultImplementation(
    _metaVaultImplementation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetPolFeeAgent(
    _polFeeAgent: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetPolFeePercentage(
    _polFeePercentage: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetPolLiquidator(
    _polLiquidator: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetPolUnwrapperTrader(
    _polUnwrapperTrader: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetPolWrapperTrader(
    _polWrapperTrader: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetRewardVaultOverride(
    _asset: string,
    _type: BigNumberish,
    _rewardVault: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetWbera(
    _wbera: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  polFeeAgent(overrides?: CallOverrides): Promise<string>;

  polFeePercentage(
    _marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  polLiquidator(overrides?: CallOverrides): Promise<string>;

  polUnwrapperTrader(overrides?: CallOverrides): Promise<string>;

  polWrapperTrader(overrides?: CallOverrides): Promise<string>;

  rewardVault(
    _asset: string,
    _type: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setDefaultRewardVaultTypeFromMetaVaultByAsset(
    _asset: string,
    _type: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  wbera(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<string>;

    berachainRewardsFactory(overrides?: CallOverrides): Promise<string>;

    bgt(overrides?: CallOverrides): Promise<string>;

    bgtIsolationModeVaultFactory(overrides?: CallOverrides): Promise<string>;

    bgtm(overrides?: CallOverrides): Promise<string>;

    bgtmIsolationModeVaultFactory(overrides?: CallOverrides): Promise<string>;

    calculateMetaVaultByAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<string>;

    createMetaVault(
      _account: string,
      _vault: string,
      overrides?: CallOverrides
    ): Promise<string>;

    dolomiteRegistry(overrides?: CallOverrides): Promise<string>;

    getAccountByMetaVault(
      _metaVault: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getAccountToAssetToDefaultType(
      _account: string,
      _asset: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getMetaVaultByAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getMetaVaultByVault(
      _vault: string,
      overrides?: CallOverrides
    ): Promise<string>;

    iBgt(overrides?: CallOverrides): Promise<string>;

    iBgtIsolationModeVaultFactory(overrides?: CallOverrides): Promise<string>;

    iBgtStakingVault(overrides?: CallOverrides): Promise<string>;

    infrared(overrides?: CallOverrides): Promise<string>;

    metaVaultImplementation(overrides?: CallOverrides): Promise<string>;

    ownerSetBerachainRewardsFactory(
      _berachainRewardsFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetBgt(_bgt: string, overrides?: CallOverrides): Promise<void>;

    ownerSetBgtIsolationModeVaultFactory(
      _bgtIsolationModeVaultFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetBgtm(_bgtm: string, overrides?: CallOverrides): Promise<void>;

    ownerSetBgtmIsolationModeVaultFactory(
      _bgtmIsolationModeVaultFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetDolomiteRegistry(
      _dolomiteRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetIBgt(_iBgt: string, overrides?: CallOverrides): Promise<void>;

    ownerSetIBgtIsolationModeVaultFactory(
      _iBgtIsolationModeVaultFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetIBgtStakingVault(
      _iBgtStakingVault: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetInfrared(
      _infrared: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetMetaVaultImplementation(
      _metaVaultImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetPolFeeAgent(
      _polFeeAgent: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetPolFeePercentage(
      _polFeePercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetPolLiquidator(
      _polLiquidator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetPolUnwrapperTrader(
      _polUnwrapperTrader: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetPolWrapperTrader(
      _polWrapperTrader: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetRewardVaultOverride(
      _asset: string,
      _type: BigNumberish,
      _rewardVault: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetWbera(_wbera: string, overrides?: CallOverrides): Promise<void>;

    polFeeAgent(overrides?: CallOverrides): Promise<string>;

    polFeePercentage(
      _marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    polLiquidator(overrides?: CallOverrides): Promise<string>;

    polUnwrapperTrader(overrides?: CallOverrides): Promise<string>;

    polWrapperTrader(overrides?: CallOverrides): Promise<string>;

    rewardVault(
      _asset: string,
      _type: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setDefaultRewardVaultTypeFromMetaVaultByAsset(
      _asset: string,
      _type: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    wbera(overrides?: CallOverrides): Promise<string>;
  };

  estimateGas: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<BigNumber>;

    berachainRewardsFactory(overrides?: CallOverrides): Promise<BigNumber>;

    bgt(overrides?: CallOverrides): Promise<BigNumber>;

    bgtIsolationModeVaultFactory(overrides?: CallOverrides): Promise<BigNumber>;

    bgtm(overrides?: CallOverrides): Promise<BigNumber>;

    bgtmIsolationModeVaultFactory(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateMetaVaultByAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createMetaVault(
      _account: string,
      _vault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    dolomiteRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    getAccountByMetaVault(
      _metaVault: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccountToAssetToDefaultType(
      _account: string,
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMetaVaultByAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMetaVaultByVault(
      _vault: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    iBgt(overrides?: CallOverrides): Promise<BigNumber>;

    iBgtIsolationModeVaultFactory(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    iBgtStakingVault(overrides?: CallOverrides): Promise<BigNumber>;

    infrared(overrides?: CallOverrides): Promise<BigNumber>;

    metaVaultImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    ownerSetBerachainRewardsFactory(
      _berachainRewardsFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetBgt(
      _bgt: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetBgtIsolationModeVaultFactory(
      _bgtIsolationModeVaultFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetBgtm(
      _bgtm: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetBgtmIsolationModeVaultFactory(
      _bgtmIsolationModeVaultFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetDolomiteRegistry(
      _dolomiteRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetIBgt(
      _iBgt: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetIBgtIsolationModeVaultFactory(
      _iBgtIsolationModeVaultFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetIBgtStakingVault(
      _iBgtStakingVault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetInfrared(
      _infrared: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetMetaVaultImplementation(
      _metaVaultImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetPolFeeAgent(
      _polFeeAgent: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetPolFeePercentage(
      _polFeePercentage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetPolLiquidator(
      _polLiquidator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetPolUnwrapperTrader(
      _polUnwrapperTrader: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetPolWrapperTrader(
      _polWrapperTrader: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetRewardVaultOverride(
      _asset: string,
      _type: BigNumberish,
      _rewardVault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetWbera(
      _wbera: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    polFeeAgent(overrides?: CallOverrides): Promise<BigNumber>;

    polFeePercentage(
      _marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    polLiquidator(overrides?: CallOverrides): Promise<BigNumber>;

    polUnwrapperTrader(overrides?: CallOverrides): Promise<BigNumber>;

    polWrapperTrader(overrides?: CallOverrides): Promise<BigNumber>;

    rewardVault(
      _asset: string,
      _type: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setDefaultRewardVaultTypeFromMetaVaultByAsset(
      _asset: string,
      _type: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    wbera(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    berachainRewardsFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bgt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bgtIsolationModeVaultFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bgtm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bgtmIsolationModeVaultFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateMetaVaultByAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createMetaVault(
      _account: string,
      _vault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    dolomiteRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAccountByMetaVault(
      _metaVault: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccountToAssetToDefaultType(
      _account: string,
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMetaVaultByAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMetaVaultByVault(
      _vault: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    iBgt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    iBgtIsolationModeVaultFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    iBgtStakingVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    infrared(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    metaVaultImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownerSetBerachainRewardsFactory(
      _berachainRewardsFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetBgt(
      _bgt: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetBgtIsolationModeVaultFactory(
      _bgtIsolationModeVaultFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetBgtm(
      _bgtm: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetBgtmIsolationModeVaultFactory(
      _bgtmIsolationModeVaultFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetDolomiteRegistry(
      _dolomiteRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetIBgt(
      _iBgt: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetIBgtIsolationModeVaultFactory(
      _iBgtIsolationModeVaultFactory: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetIBgtStakingVault(
      _iBgtStakingVault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetInfrared(
      _infrared: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetMetaVaultImplementation(
      _metaVaultImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetPolFeeAgent(
      _polFeeAgent: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetPolFeePercentage(
      _polFeePercentage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetPolLiquidator(
      _polLiquidator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetPolUnwrapperTrader(
      _polUnwrapperTrader: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetPolWrapperTrader(
      _polWrapperTrader: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetRewardVaultOverride(
      _asset: string,
      _type: BigNumberish,
      _rewardVault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetWbera(
      _wbera: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    polFeeAgent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    polFeePercentage(
      _marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    polLiquidator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    polUnwrapperTrader(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    polWrapperTrader(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rewardVault(
      _asset: string,
      _type: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setDefaultRewardVaultTypeFromMetaVaultByAsset(
      _asset: string,
      _type: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    wbera(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
